// <auto-generated />
using AopTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AopTest.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190801080130_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("AopTest.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Crash",
                            Name = "Crash"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Sol",
                            Name = "Sol"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Test",
                            Name = "Test"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
